### PR TITLE
Cross-platform and better.

### PR DESCRIPTION
**Pull request by aedorado**

### CODE REVIEW

**Comment by vivekanand1101** [comment]
-  Two most important files for getting this project up and running are missing. Why exactly would you   delete them?  `Readme.md` and `requirements.txt`

Can you add them back and update them according to whatever changes you have done?  This would enable me to check this PR locally.

Also, pls avoid doing small but still, pythonic crimes such as: "from abc import *"  :)

**Comment by aedorado** [comment]
Sure I'll add them.

**Comment by aedorado** [comment]
Done.

**Comment by aedorado** [comment]
Anything left to be done before you gonna merge this?

**Comment by vivekanand1101** [comment]
I just want to verify it locally. :)

**Pull request merged**
